#####################################################################
# User settings must be in $XI_CONFIG/preferences.xiconfig, where   #
# '$XI_CONFIG' is the Xi configuration directory for your platform. #
#                                                                   #
# These settings can also be overridden for a particular syntax;    #
# add your overrides in (for example) '$XI_CONFIG/rust.xiconfig'.   #
#####################################################################


# The width of a tab, in spaces.
tab_size = 4

# Insert spaces when the tab key is pressed.
translate_tabs_to_spaces = true

# If translate_tabs_to_spaces is true, backspace will delete multiple
# spaces, up to the previous tab stop.
use_tab_stops = true

# List of paths to additional plugins
plugin_search_path = []

font_face = "Inconsolata"

# In points
font_size = 14

# Automatically match current indentation level on newline.
auto_indent = true

# Allow scrolling past the last line of a document.
scroll_past_end = false

# If non-zero, indicates the column at which lines will be wrapped.
wrap_width = 0

# If true, wraps lines at the edge of the view. Overrides 'wrap_width'.
word_wrap = false

# Detect tab and newline settings on file open
autodetect_whitespace = true

# Ensure file ends in a newline when saving
save_with_newline = true
