[package]
name = "xi-core"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]

[dependencies]
serde = "0.8"
serde_json = "0.8"
time = "0.1"

[dependencies.xi-rope]
path = "rope"

[dependencies.xi-unicode]
path = "unicode"

[dependencies.xi-rpc]
path = "rpc"
