[package]
name = "xi-core"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]

[dependencies]
serde = "0.8"
serde_json = "0.8"
time = "0.1"

[dependencies.xi-rope]
path = "rope"

[dependencies.xi-unicode]
path = "unicode"

[dependencies.xi-rpc]
path = "rpc"

[target.'cfg(target_os = "fuchsia")'.dependencies]
magenta = { path = "../../../rust/magenta-rs" }
mxruntime = { path = "../../../rust/mxruntime" }
fidl = { path = "../../../lib/fidl/rust/fidl" }
apps_xi-editor_rust_interfaces = { path = "../../../out/debug-x86-64/gen/apps/xi-editor/rust/interfaces" }
apps_modular_services_application_service_provider = { path = "../../../out/debug-x86-64/gen/apps/modular/services/application/service_provider" }
